version: '3.8'

services:
  # Django Social Media Application
  web:
    build: .
    container_name: social-media-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=social_media.production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DATABASE_HOST=192.168.91.110
      - DATABASE_PORT=3306
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - REDIS_HOST=192.168.91.110
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=192.168.91.110:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=social-media-app
      - MINIO_USE_HTTPS=false
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    depends_on:
      - mysql
      - redis
      - minio
    networks:
      - social-media-network
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL Database (if you want to run locally)
  mysql:
    image: mysql:8.0
    container_name: social-media-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - social-media-network
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache (if you want to run locally)
  redis:
    image: redis:7-alpine
    container_name: social-media-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - social-media-network
    command: redis-server --appendonly yes

  # MinIO Object Storage (if you want to run locally)
  minio:
    image: minio/minio:latest
    container_name: social-media-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - social-media-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: social-media-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/var/www/static:ro
    depends_on:
      - web
    networks:
      - social-media-network

volumes:
  mysql_data:
  redis_data:
  minio_data:

networks:
  social-media-network:
    driver: bridge 