version: '3.8'

services:
  # Django Social Media Application
  web:
    build: .
    container_name: social-media-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=social_media.production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DATABASE_HOST=192.168.91.110
      - DATABASE_PORT=3306
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - REDIS_HOST=192.168.91.110
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=192.168.91.110:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=social-media-app
      - MINIO_USE_HTTPS=false
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    extra_hosts:
      - "192.168.91.110:host-gateway"
    networks:
      - social-media-network
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  social-media-network:
    driver: bridge 