apiVersion: v1
kind: PersistentVolume
metadata:
  name: social-media-pv
  labels:
    app: social-media-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: social-media-storage
  hostPath:
    path: /data/social-media
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-media-pvc
  namespace: social-media
  labels:
    app: social-media-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: social-media-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: social-media-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
# MySQL storage (hostPath, simple local persistence)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-hostpath
  labels:
    app: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
    path: /data/mysql
    type: DirectoryOrCreate

---
# Redis storage (hostPath)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage
  hostPath:
    path: /data/redis
    type: DirectoryOrCreate

---
# MinIO storage (hostPath)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-storage
  hostPath:
    path: /data/minio
    type: DirectoryOrCreate
---
# Static files volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: social-media-static-pv
  labels:
    app: social-media-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: social-media-static-storage
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: /exports/social-media-static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-media-static-pvc
  namespace: social-media
  labels:
    app: social-media-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: social-media-static-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: social-media-static-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
